# Generated by Django 5.2.5 on 2026-08-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustoz_ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lesson',
            new_name='ustoz_lesso_subject_edd458_idx',
            old_name='ustoz_lesson_sub_act_idx',
        ),
        migrations.RenameIndex(
            model_name='ustozquestion',
            new_name='ustoz_quest_lesson__4e8615_idx',
            old_name='ustoz_q_les_act_idx',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ustozquestion',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text="To'g'ri javob izoh (ixtiyoriy)"),
        ),
        migrations.AlterField(
            model_name='ustozquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
