# Generated by Django 5.0.6 on 2026-06-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('author_name', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_by_telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'author_questions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='author_ques_status_c73e19_idx'), models.Index(fields=['telegram_id', 'status'], name='author_ques_telegra_41b5d4_idx')],
            },
        ),
    ]
