# Generated by Django 5.0.6 on 2026-05-22 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BattleChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("challenger_team_id", models.UUIDField(db_index=True)),
                ("opponent_team_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("accepted", "Qabul qilindi"),
                            ("in_progress", "Jarayonda"),
                            ("finished", "Tugadi"),
                            ("declined", "Rad etildi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_round_number", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "battle_challenges",
            },
        ),
        migrations.CreateModel(
            name="BattleRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_id", models.UUIDField()),
                ("round_number", models.IntegerField()),
                ("time_limit_seconds", models.IntegerField(default=30)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="battles.battlechallenge",
                    ),
                ),
            ],
            options={
                "db_table": "battle_rounds",
            },
        ),
        migrations.CreateModel(
            name="BattleAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("telegram_id", models.BigIntegerField()),
                ("team_id", models.UUIDField()),
                ("answer", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                ("response_time_ms", models.IntegerField(default=0)),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="battles.battlechallenge",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="battles.battleround",
                    ),
                ),
            ],
            options={
                "db_table": "battle_answers",
                "unique_together": {("round", "telegram_id")},
            },
        ),
    ]
