# Generated by Django 5.0.6 on 2026-05-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleanswer',
            name='team_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='battleanswer',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='battleanswer',
            index=models.Index(fields=['round', 'telegram_id'], name='battle_answ_round_i_fbcd3d_idx'),
        ),
        migrations.AddIndex(
            model_name='battleanswer',
            index=models.Index(fields=['battle', 'team_id'], name='battle_answ_battle__5f5a04_idx'),
        ),
    ]
