# Generated by Django 5.0.6 on 2026-06-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_alter_battleanswer_team_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlechallenge',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('finished', 'Tugadi'), ('declined', 'Rad etildi')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='battleround',
            name='time_limit_seconds',
            field=models.IntegerField(default=60),
        ),
    ]
