# Generated by Django 5.2.5 on 2026-08-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZtQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('answer', models.TextField()),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zakovat stoli savoli',
                'verbose_name_plural': 'Zakovat stoli savollari',
                'db_table': 'zakovat_table_question',
                'ordering': ['sector'],
            },
        ),
        migrations.CreateModel(
            name='ZtRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('admin_telegram_id', models.BigIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('waiting', "Jamoa yig'ilmoqda (lobbi)"), ('team_confirmed', 'Jamoa tasdiqlangan — boshlanishi kutilmoqda'), ('in_progress', "O'yin jarayonda — ot aylantirilishi kutilmoqda"), ('discussion', "Savol o'qildi — jamoa muhokama qilmoqda"), ('awaiting_answer', 'Kapitan yakuniy javobini kutmoqda'), ('verifying', 'Admin javobni baholamoqda'), ('finished', "O'yin tugagan")], db_index=True, default='waiting', max_length=20)),
                ('team_score', models.PositiveSmallIntegerField(default=0)),
                ('fans_score', models.PositiveSmallIntegerField(default=0)),
                ('discussion_deadline', models.DateTimeField(blank=True, null=True)),
                ('captain_answer_text', models.TextField(blank=True, default='')),
                ('captain_answer_is_voice', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, choices=[('team', "Jamoa (o'yinchilar)"), ('fans', 'Muxlislar'), ('draw', 'Durrang')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='zakovat_table.ztquestion')),
            ],
            options={
                'verbose_name': 'Zakovat stoli xonasi',
                'verbose_name_plural': 'Zakovat stoli xonalari',
                'db_table': 'zakovat_table_room',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ztquestion',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='zakovat_table.ztroom'),
        ),
        migrations.AlterUniqueTogether(
            name='ztquestion',
            unique_together={('room', 'sector')},
        ),
        migrations.CreateModel(
            name='ZtPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('display_name', models.CharField(max_length=120)),
                ('seat', models.PositiveSmallIntegerField()),
                ('is_captain', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='zakovat_table.ztroom')),
            ],
            options={
                'verbose_name': "Zakovat stoli o'yinchisi",
                'verbose_name_plural': "Zakovat stoli o'yinchilari",
                'db_table': 'zakovat_table_player',
                'ordering': ['seat'],
                'unique_together': {('room', 'seat'), ('room', 'telegram_id')},
            },
        ),
        migrations.CreateModel(
            name='ZtSpectator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectators', to='zakovat_table.ztroom')),
            ],
            options={
                'verbose_name': 'Zakovat stoli muxlisi',
                'verbose_name_plural': 'Zakovat stoli muxlislari',
                'db_table': 'zakovat_table_spectator',
                'unique_together': {('room', 'telegram_id')},
            },
        ),
    ]
