# Generated by Django 5.0.6 on 2026-06-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_telegram_id', models.BigIntegerField(db_index=True)),
                ('author_name', models.CharField(default='', max_length=200)),
                ('text', models.TextField(blank=True, default='')),
                ('media_type', models.CharField(blank=True, choices=[('', "Yo'q"), ('image', 'Rasm'), ('video', 'Video')], default='', max_length=10)),
                ('media_file_id', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Admin Post',
                'verbose_name_plural': 'Admin Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
