release: python manage.py migrate --noinput && python manage.py collectstatic --noinput
web: gunicorn zakovat.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --access-logfile - --error-logfile - --log-level info
