-- Zakovat — namuna savollar.
-- Supabase SQL editorida bir marta bajaring (questions jadvali yaratilgandan keyin).

insert into questions (text, correct_answer, category, difficulty) values
-- Geografiya
('O''zbekistonning poytaxti qaysi shahar?', 'Toshkent', 'Geografiya', 'easy'),
('Dunyodagi eng katta okean qaysi?', 'Tinch okeani', 'Geografiya', 'easy'),
('Dunyodagi eng baland tog'' cho''qqisi qaysi?', 'Everest', 'Geografiya', 'easy'),
('Afrikaning eng uzun daryosi qaysi?', 'Nil', 'Geografiya', 'medium'),
('O''zbekiston qaysi qit''ada joylashgan?', 'Osiyo', 'Geografiya', 'easy'),
('Sahroi Kabir cho''li qaysi qit''ada joylashgan?', 'Afrika', 'Geografiya', 'easy'),
('Aholisi eng ko''p davlat qaysi?', 'Hindiston', 'Geografiya', 'medium'),
('Yer sayyorasining tabiiy yo''ldoshi nima?', 'Oy', 'Geografiya', 'easy'),
('Eng sho''r dengiz qaysi?', 'O''lik dengiz', 'Geografiya', 'hard'),
('Qaysi materik eng kichik?', 'Avstraliya', 'Geografiya', 'medium'),
('Toshkent qaysi daryo bo''yida joylashgan?', 'Chirchiq', 'Geografiya', 'hard'),
('Samarqand shahri qaysi davlatda joylashgan?', 'O''zbekiston', 'Geografiya', 'easy'),
-- Tarix
('O''zbekiston mustaqillikni qaysi yili qo''lga kiritdi?', '1991', 'Tarix', 'easy'),
('Amir Temur qaysi shaharda tug''ilgan?', 'Shahrisabz', 'Tarix', 'medium'),
('Alisher Navoiy qaysi asrda yashagan?', 'XV asr', 'Tarix', 'medium'),
('Ikkinchi jahon urushi qaysi yili tugagan?', '1945', 'Tarix', 'easy'),
('Kosmosga uchgan birinchi inson kim?', 'Yuriy Gagarin', 'Tarix', 'easy'),
('Amerika qit''asini kim kashf etgan?', 'Xristofor Kolumb', 'Tarix', 'medium'),
('Mirzo Ulug''bek qaysi fan bilan mashhur?', 'Astronomiya', 'Tarix', 'medium'),
('"Boburnoma" asarini kim yozgan?', 'Bobur', 'Tarix', 'medium'),
('O''zbekistonning birinchi Prezidenti kim edi?', 'Islom Karimov', 'Tarix', 'easy'),
('Sovet Ittifoqi qaysi yili tarqaldi?', '1991', 'Tarix', 'medium'),
('Toshkent metrosi qaysi yili ochilgan?', '1977', 'Tarix', 'hard'),
('Buyuk ipak yo''li asosan qaysi ikki tomonni bog''lagan?', 'Sharq va G''arb', 'Tarix', 'medium'),
-- Fan
('Suv necha gradusda qaynaydi?', '100', 'Fan', 'easy'),
('Insonning normal tana harorati necha gradus?', '36.6', 'Fan', 'easy'),
('Suvning kimyoviy formulasi qanday?', 'H2O', 'Fan', 'easy'),
('Inson tanasida nechta suyak bor?', '206', 'Fan', 'medium'),
('Eng yengil kimyoviy element qaysi?', 'Vodorod', 'Fan', 'medium'),
('O''simliklar havodan qaysi gazni yutadi?', 'Karbonat angidrid', 'Fan', 'medium'),
('Inson tanasida qaysi a''zo qonni tozalaydi?', 'Buyrak', 'Fan', 'medium'),
('Tabiatdagi eng qattiq modda qaysi?', 'Olmos', 'Fan', 'medium'),
('Tovush qaysi muhitda tarqalmaydi?', 'Vakuum', 'Fan', 'hard'),
('Insonda nechta yurak bor?', '1', 'Fan', 'easy'),
('Quyosh sistemasida nechta sayyora bor?', '8', 'Fan', 'medium'),
('Yer Quyosh atrofini necha kunda bir marta aylanadi?', '365', 'Fan', 'easy'),
-- Matematika
('15 ni 8 ga ko''paytiring', '120', 'Matematika', 'easy'),
('144 sonining kvadrat ildizi nechaga teng?', '12', 'Matematika', 'medium'),
('100 dan 37 ni ayiring', '63', 'Matematika', 'easy'),
('Uchburchak nechta burchakka ega?', '3', 'Matematika', 'easy'),
('7 ni 9 ga ko''paytiring', '63', 'Matematika', 'easy'),
('1 kilometrda necha metr bor?', '1000', 'Matematika', 'easy'),
('12 ni 12 ga ko''paytiring', '144', 'Matematika', 'easy'),
('256 sonining yarmi nechaga teng?', '128', 'Matematika', 'easy'),
('Eng kichik tub son qaysi?', '2', 'Matematika', 'medium'),
('Doira aylanasini hisoblashda ishlatiladigan son nomi nima?', 'Pi', 'Matematika', 'medium'),
-- Umumiy
('O''zbekistonning milliy valyutasi nima?', 'So''m', 'Umumiy', 'easy'),
('Bir yilda necha oy bor?', '12', 'Umumiy', 'easy'),
('Bir haftada necha kun bor?', '7', 'Umumiy', 'easy'),
('Kamalakda nechta rang bor?', '7', 'Umumiy', 'easy'),
('Shahmat taxtasida nechta katak bor?', '64', 'Umumiy', 'medium'),
('Futbol jamoasida maydonda nechta o''yinchi bo''ladi?', '11', 'Umumiy', 'easy'),
('Insonning eng katta a''zosi qaysi?', 'Teri', 'Umumiy', 'medium'),
('Asalni qaysi hasharot ishlab chiqaradi?', 'Asalari', 'Umumiy', 'easy'),
('Olimpiada o''yinlari necha yilda bir marta o''tkaziladi?', '4', 'Umumiy', 'medium'),
('Quruqlikdagi eng tez yuguruvchi hayvon qaysi?', 'Gepard', 'Umumiy', 'medium'),
('O''zbekiston davlat bayrog''ida nechta rang bor?', '3', 'Umumiy', 'medium'),
('"Alpomish" o''zbek xalqining qanday asari hisoblanadi?', 'Doston', 'Umumiy', 'hard'),
('Bir sutkada necha soat bor?', '24', 'Umumiy', 'easy'),
('Pianino qanday cholg''u asboblari turiga kiradi?', 'Klavishli', 'Umumiy', 'hard');
