# Generated by Django 5.0.6 on 2026-06-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_milestone_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text="Premium tizimi yoqilganmi (False = hamma erkin, hech narsa o'zgarmaydi)")),
                ('price', models.PositiveIntegerField(default=0, help_text="Ko'rsatish narxi (to'lov yo'q)")),
                ('currency', models.CharField(default="so'm", max_length=20)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Premium muddati (kun). Grant berishda default sifatida ishlatiladi.')),
                ('benefits', models.TextField(blank=True, default='')),
                ('section_limits', models.JSONField(default=dict, help_text="Bo'lim cheklovlari: {round, daily, battle, svoyak, gameroom} har biri {limited: bool, free_limit: int (kunlik)} strukturasida.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'premium_settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='premium_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
