# Generated by Django 5.0.6 on 2026-06-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerooms', '0002_hash_room_password_length'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gamequestion',
            new_name='gameroom_qu_room_id_346355_idx',
            old_name='gameroom_q_room_status_idx',
        ),
        migrations.RenameIndex(
            model_name='gamequestion',
            new_name='gameroom_qu_room_id_812027_idx',
            old_name='gameroom_q_room_order_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='gameroom_su_questio_e918e1_idx',
            old_name='gameroom_sub_q_p_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='gameroom_su_questio_4c0088_idx',
            old_name='gameroom_sub_q_correct_idx',
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text="Admin 'active' qilgan server vaqti", null=True),
        ),
    ]
