# Generated by Django 5.0.6 on 2026-05-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SvoyakCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('icon_emoji', models.CharField(blank=True, default='', max_length=10)),
                ('language', models.CharField(db_index=True, default='uz-latn', max_length=10)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Svoyak kategoriya',
                'verbose_name_plural': 'Svoyak kategoriyalar',
                'db_table': 'svoyak_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SvoyakRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('host_telegram_id', models.BigIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('lobby', 'Lobbi (kutish)'), ('playing', "O'yinda"), ('paused', 'Pauza'), ('finished', 'Tugagan')], db_index=True, default='lobby', max_length=10)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Svoyak room',
                'verbose_name_plural': 'Svoyak roomlar',
                'db_table': 'svoyak_room',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SvoyakQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_tier', models.PositiveSmallIntegerField(choices=[(10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50')], db_index=True)),
                ('text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('wrong_answers', models.JSONField(blank=True, default=list)),
                ('question_type', models.CharField(choices=[('text', 'Erkin javob (matn)'), ('abcd', 'A/B/C/D variantlar')], default='abcd', max_length=10)),
                ('media_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='svoyak.svoyakcategory')),
            ],
            options={
                'verbose_name': 'Svoyak savol',
                'verbose_name_plural': 'Svoyak savollar',
                'db_table': 'svoyak_question',
            },
        ),
        migrations.CreateModel(
            name='SvoyakPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('display_name', models.CharField(max_length=120)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('connected', 'Ulangan'), ('disconnected', 'Uzilgan'), ('kicked', 'Chiqarib yuborilgan')], default='connected', max_length=15)),
                ('last_buzz_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('can_pick', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='svoyak.svoyakroom')),
            ],
            options={
                'verbose_name': "Svoyak o'yinchi",
                'verbose_name_plural': "Svoyak o'yinchilar",
                'db_table': 'svoyak_player',
                'ordering': ['-score', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='SvoyakRoomCategorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_by_value', models.JSONField(default=dict)),
                ('used_value_tiers', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svoyak.svoyakcategory')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_snapshots', to='svoyak.svoyakroom')),
            ],
            options={
                'verbose_name': 'Svoyak xona kategoriya snapshot',
                'verbose_name_plural': 'Svoyak xona kategoriya snapshotlar',
                'db_table': 'svoyak_room_category_snapshot',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SvoyakRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('reading', "Savol o'qilmoqda (BUZZ rejimi yopiq)"), ('waiting_buzz', 'BUZZ kutilmoqda (ochiq)'), ('answering', 'Javob berilmoqda'), ('completed', 'Tugagan'), ('skipped', 'Hech kim javob bermadi')], default='reading', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('buzz_opened_at', models.DateTimeField(blank=True, null=True)),
                ('buzz_winner_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('buzz_attempts', models.JSONField(blank=True, default=list)),
                ('answer_text', models.TextField(blank=True, default='')),
                ('answer_correct', models.BooleanField(blank=True, null=True)),
                ('score_delta', models.IntegerField(default=0)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('buzz_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='svoyak.svoyakplayer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='svoyak.svoyakquestion')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='svoyak.svoyakroom')),
            ],
            options={
                'verbose_name': 'Svoyak raund',
                'verbose_name_plural': 'Svoyak raundlar',
                'db_table': 'svoyak_round',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='svoyakroom',
            name='current_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='svoyak.svoyakround'),
        ),
        migrations.AddIndex(
            model_name='svoyakquestion',
            index=models.Index(fields=['category', 'value_tier', 'is_active'], name='svoyak_ques_categor_f61e48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='svoyakplayer',
            unique_together={('room', 'telegram_id')},
        ),
        migrations.AlterUniqueTogether(
            name='svoyakroomcategorysnapshot',
            unique_together={('room', 'category')},
        ),
        migrations.AddIndex(
            model_name='svoyakround',
            index=models.Index(fields=['room', 'status'], name='svoyak_roun_room_id_308c79_idx'),
        ),
    ]
