# Generated by Django 5.0.6 on 2026-06-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svoyak', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='svoyakplayer',
            name='role',
            field=models.CharField(choices=[('player', "O'yinchi"), ('coordinator', "Koordinator (savol o'quvchi)")], default='player', max_length=15),
        ),
    ]
