# Generated by Django 5.0.6 on 2026-05-23 13:00

from django.db import migrations, models


def bump_existing_to_six(apps, schema_editor):
    """Eski default (4) bilan yaratilgan jamoalarni 6 a'zoga ko'taramiz."""
    Team = apps.get_model("teams", "Team")
    Team.objects.filter(max_members__lt=6).update(max_members=6)


def back_to_four(apps, schema_editor):
    """Reverse — yangi default (6) bilan yaratilganlarni 4 ga tushirsak agar shu kerak bo'lsa."""
    Team = apps.get_model("teams", "Team")
    Team.objects.filter(max_members=6).update(max_members=4)


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='max_members',
            field=models.IntegerField(default=6),
        ),
        migrations.RunPython(bump_existing_to_six, back_to_four),
    ]
