# Generated by Django 5.0.6 on 2026-05-24 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_max_members_six'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='teams.team')),
            ],
            options={
                'db_table': 'team_chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['team', 'created_at'], name='team_chat_m_team_id_643ab8_idx')],
            },
        ),
    ]
