# Generated by Django 5.0.6 on 2026-05-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='owner_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
