# Generated by Django 5.0.6 on 2026-06-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_daily_answer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyanswer',
            name='unique_daily_answer_per_question',
        ),
        migrations.RemoveConstraint(
            model_name='dailychallengeentry',
            name='unique_daily_entry_per_user',
        ),
        migrations.RenameIndex(
            model_name='dailychallengeentry',
            new_name='daily_chall_telegra_a568c6_idx',
            old_name='daily_entry_user_date_idx',
        ),
        migrations.AlterField(
            model_name='dailyanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dailychallengeentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdailystreak',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyanswer',
            unique_together={('telegram_id', 'date', 'question_id')},
        ),
        migrations.AlterUniqueTogether(
            name='dailychallengeentry',
            unique_together={('telegram_id', 'date')},
        ),
    ]
