# Generated by Django 5.0.6 on 2026-06-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_chat_enabled', models.BooleanField(default=True, help_text="Battle o'yinida jamoa chat ko'rinsinmi")),
                ('battle_chat_poll_interval_ms', models.PositiveIntegerField(default=4000, help_text='Chat yangilanish intervali (millisoniya, 1000-30000)')),
                ('battle_show_correct_on_timeout', models.BooleanField(default=True, help_text="Vaqt tugaganda to'g'ri javobni ko'rsatsinmi")),
                ('tts_enabled', models.BooleanField(default=True, help_text="TTS (ovozli o'qish) funksiyasi global yoqilganmi")),
                ('tts_default_muted', models.BooleanField(default=False, help_text="Yangi foydalanuvchilar uchun ovoz default o'chirilganmi")),
                ('difficulty_easy_enabled', models.BooleanField(default=True, help_text="'Oson' qiyinlik darajasi o'yinda ko'rinsinmi")),
                ('difficulty_medium_enabled', models.BooleanField(default=True, help_text="'O'rtacha' qiyinlik darajasi o'yinda ko'rinsinmi")),
                ('difficulty_hard_enabled', models.BooleanField(default=True, help_text="'Qiyin' qiyinlik darajasi o'yinda ko'rinsinmi")),
                ('svoyak_coordinator_enabled', models.BooleanField(default=True, help_text="Svoyak'da koordinator roliga qo'shilish mumkinmi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ilova sozlamalari',
                'db_table': 'app_settings',
            },
        ),
    ]
