# Generated by Django 5.0.6 on 2026-05-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wrong_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name='questionreport',
            unique_together={('question', 'reported_by')},
        ),
    ]
